deployment:
  kind: DaemonSet

service:
  type: NodePort
  spec:
    externalTrafficPolicy: Local

api:
  insecure: true # serves dashboard on the traefik entrypoint (port 8080) without auth

ingressRoute:
  dashboard:
    enabled: true
    matchRule: Host(`dashboard.localhost`)
    entryPoints:
      - web

ports:
  traefik:
    hostPort: 8080 # dashboard at http://<any-node-ip>:8080/dashboard/ from LAN
  web:
    nodePort: 30080
    forwardedHeaders:
      trustedIPs:
        - "192.168.0.180/32" # NPM NAS IP
  websecure:
    nodePort: 30443
    forwardedHeaders:
      trustedIPs:
        - "192.168.0.180/32"

metrics:
  prometheus:
    service:
      enabled: true
    serviceMonitor:
      enabled: true

providers:
  kubernetesCRD:
    allowCrossNamespace: true
  kubernetesGateway:
    enabled: true

gateway:
  listeners:
    web:
      namespacePolicy:
        from: All
