prometheus:
  prometheusSpec:
    additionalScrapeConfigs:
      - job_name: pihole
        static_configs:
          - targets:
              - 192.168.0.180:9617
              - 192.168.0.104:9617
              - 192.168.0.105:9617
              - 192.168.0.202:9617
              - 192.168.0.201:9617
              - 192.168.0.203:9617
              - 192.168.0.204:9617
      - job_name: nas-postgres
        static_configs:
          - targets: [ "192.168.0.180:9432" ]
      - job_name: nas-mariadb
        static_configs:
          - targets: [ "192.168.0.180:9104" ]
      - job_name: nas-redis
        static_configs:
          - targets: [ "192.168.0.180:9121" ]
