prometheus:
  prometheusSpec:
    serviceMonitorSelectorNilUsesHelmValues: false
    replicas: 2
    scrapeInterval: 60s
    evaluationInterval: 60s
    storageSpec:
      volumeClaimTemplate:
        spec:
          storageClassName: nfs-nas
          accessModes: ["ReadWriteOnce"]
          resources:
            requests:
              storage: 10Gi
    retention: 14d
    retentionSize: 7GB # need to check if I am hitting this limit

grafana:
  enabled: true
  replicas: 1
  adminUser: admin
  adminPassword: "Homelab@123"
  ingress:
    enabled: false
  service:
    type: LoadBalancer
    annotations:
      metallb.universe.tf/loadBalancerIPs: "192.168.0.20"
  persistence:
    enabled: true
    type: sts
    storageClassName: nfs-nas
    accessModes:
      - ReadWriteOnce
    size: 1Gi
    finalizers:
      - kubernetes.io/pvc-protection
  assertNoLeakedSecrets: false
  grafana.ini:
    database:
      type: postgres
      host: nas-postgres.nas-services.svc.cluster.local:5432
      name: grafana
      user: grafana
      password: grafana
      ssl_mode: disable

# alertmanager:
#   alertmanagerSpec: {}
