apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: openwebui
  namespace: argocd
spec:
  project: default
  sources:
    - repoURL: https://helm.openwebui.com/
      chart: open-webui
      targetRevision: 8.4.0
      helm:
        valueFiles:
          - $values/values/openwebui.yaml
    - repoURL: "https://github.com/SuperSecureHuman/homelab-argo.git"
      targetRevision: main
      ref: values
  destination:
    server: https://kubernetes.default.svc
    namespace: openwebui
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true
