apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: grafana-db-credentials
  namespace: monitoring
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: infisical-cluster-store
  refreshInterval: 1h
  target:
    name: grafana-db-credentials
    creationPolicy: Owner
  data:
    - secretKey: password
      remoteRef:
        key: GRAFANA_DB_PASSWORD
